### ISSUE TITLE
latency

### ISSUE THREAD

**Issue by hyunjaecho94** [lgsvl/PythonAPI#13]
Apollo does not avoid a simple collision. The modules in Module Controller all work (localization, perception, planning, traffic light, transform, control, routing, and prediction stay on once enabled). I am thinking this may be an issue with latency, and Apollo does not perceive an approaching vehicle until it's too late and hence results in a collision. If I manually pause (put on break) briefly, Apollo is able to perceive the approaching vehicle and stop itself. Could this be an issue of latency? If so, where could the latency be from?

**Comment by lemketron** [comment]
This is an old issue but it's worth pointing out that we have pushed changes to apollo master (v6.0) that allow apollo to use the LGSVL simulator's clock sensor instead of using real time. This should help with any latency issues in apollo, especially in the case where users are making several python API calls in between stepping the simulator (for example, calling sim.run with a run time of 0.1s).

You can find out more in the [Clock Sensor documentation](https://www.lgsvlsimulator.com/docs/sensor-json-options/#clock)
