### ISSUE TITLE
Apollo Car Doesn't Drive

### ISSUE THREAD

**Issue by kesav-v** [lgsvl/PythonAPI#37]
When I run the following script which is based on the [Dreamview API Example](https://www.svlsimulator.com/docs/python-api/dreamview-api/#example), the Apollo car doesn't move:

```
import os
import lgsvl
​
SIMULATOR_HOST = os.environ.get("SIMULATOR_HOST", "127.0.0.1")
SIMULATOR_PORT = int(os.environ.get("SIMULATOR_PORT", 8181))
BRIDGE_HOST = os.environ.get("BRIDGE_HOST", "127.0.0.1")
BRIDGE_PORT = int(os.environ.get("BRIDGE_PORT", 9090))
​
sim = lgsvl.Simulator(SIMULATOR_HOST, SIMULATOR_PORT)
if sim.current_scene == "BorregasAve":
    sim.reset()
else:
    sim.load("BorregasAve")
​
spawns = sim.get_spawn()
​
state = lgsvl.AgentState()
# state.transform = spawns[0]
state.transform = lgsvl.Transform(position=lgsvl.Vector(348.98876953125, -7.54502630233765, -107.056831359863), rotation=lgsvl.Vector(0, 280.98388671875, 0))
​
ego = sim.add_agent(lgsvl.wise.DefaultAssets.ego_lincoln2017mkz_apollo5_modular, lgsvl.AgentType.EGO, state)
ego.connect_bridge(lgsvl.wise.SimulatorSettings.bridge_host, lgsvl.wise.SimulatorSettings.bridge_port)
​
# Dreamview setup
dv = lgsvl.dreamview.Connection(sim, ego, BRIDGE_HOST)
dv.set_hd_map('Borregas Ave')
dv.set_vehicle('Lincoln2017MKZ LGSVL')
modules = [
    'Localization',
    'Perception',
    'Third Party Perception',
    'Transform',
    'Routing',
    'Prediction',
    'Planning',
    'Camera',
    'Traffic Light',
    'Control'
]
destination = spawns[0].destinations[0]
​
transform = lgsvl.Transform(position=lgsvl.Vector(348.98876953125, -7.54502630233765, -107.056831359863), rotation=lgsvl.Vector(0, 280.98388671875, 0))
gps_coords = sim.map_to_gps(transform)
print(gps_coords)
dv.setup_apollo(322.1101076679857, -135.03040882097315, modules)
# dv.setup_apollo(destination.position.x, destination.position.z, modules)
​
sim.run()
```

However, if I uncomment the lines that use `spawns` and `destination.position` as the start and endpoints, the car drives. We verified that the positions we manually generated here are actually on the map, so we were wondering what the issue might be. Thanks in advance!

**Comment by hadiTab** [comment]
The spawn and destination points use Unity Coordinates. Are you taking that into account when manually specifying the points?

**Comment by kesav-v** [comment]
Yes, we generated the points using Scenic and we were able to check that the points were on the map, using the `map_to_gps` function and manually inspecting the map in the Dreamview UI.

**Comment by hadiTab** [comment]
I just tested this out. Were you using this with 2020.06 or 2021.1? It needs some changes to work with 2021.1 but overall the issue seams to be with the spawn location you are using. The spawn location is in the intersection (on the HD map). In general, Apollo doesn't behave well if you spawn in the intersection. I believe the reason is that it may infer the ego to be in a different lane than you intend it to be in because lane lines all cross each other in the intersection. By moving the car spawn point a little forward (past the lane turning to the right) or back out of the intersection I can get it to behave correctly.

For example try: `state.transform = lgsvl.Transform(position=lgsvl.Vector(340.98876953125, -7.54502630233765, -107.056831359863), rotation=lgsvl.Vector(0, 280.98388671875, 0))`
Or: `state.transform = lgsvl.Transform(position=lgsvl.Vector(360.98876953125, -7.54502630233765, -111.056831359863), rotation=lgsvl.Vector(0, 280.98388671875, 0))`

**Comment by kesav-v** [comment]
This seems to work. Thanks!
